### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jacmet** [nhorman/dropwatch#14]
Hello,

We're included dropwatch for a number of years in Buildroot, but recently noticed a potential licensing issue regarding readline. Can you clarify please? Judging by the lack of "any later version", dropwatch is GPL-2.0 only, but it links against libreadline which is GPL-3.0+.

Those two licenses are not compatible, so that is no good. What is the effective license of dropwatch linked with libreadline supposed to be?

**Comment by nhorman** [comment]
Its a typo, dropwatch should be GPLv2 or later, I'll fix it shortly

**Comment by jacmet** [comment]
@nhorman I still do not see any license changes in the repo?

**Comment by nhorman** [comment]
Because I went an looked, and the COPYING file very clearly does state that the license is GPL-v2 or later, making it not strictly GPLv2, but for claritys sake, I'm attaching SPDX headers to all the source

**Comment by jacmet** [comment]
Yes, the generic GPL-2.0 COPYING file mentions the "any later" text, but this is normally clarified in the GPL headers in the individual source files.

E.G. the GPL header in src/main.c states:

 * This program file is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; version 2 of the License.

So nothing about "(at your option) any later version"
