### ISSUE TITLE
hanging test

### ISSUE THREAD

**Issue by onlyjob** [nhorman/dropwatch#16]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952614, apparently `make  check-TESTS` may hang for a long time. I could not reproduce the effect on my system but I hope that you might know better what might be causing the problem. See the full build log here:

  http://qa-logs.debian.net/2020/02/25/dropwatch_1.5.1-2_unstable.log

Thanks.

**Comment by nhorman** [comment]
Not off the top of my head no, though the logs aren't complete.  Usually CI systems are configured to dump out the contents of rundropwatch.sh.log when something fails or times out, which is where the information on whats going on here is kept.  Is there any way you can provide that log?

**Comment by onlyjob** [comment]
Unfortunately I have no way of providing the log. Even modifying the package dump the log to STDOUT/STDERR on error might be problematic because build environment is teared down on timeout...

Maybe log could be just sent to STDERR instead of being saved to file?

**Comment by nhorman** [comment]
sure, you're welcome to modify rundropwatch.sh to cat the log in the script.
