### ISSUE TITLE
CI is currently broken due to ubuntu error in libpcap package

### ISSUE THREAD

**Issue by nhorman** [nhorman/dropwatch#20]
https://bugs.launchpad.net/ubuntu/+source/libpcap/+bug/1865501

**Comment by idosch** [comment]
Neil, as a workaround, can we add 'libpcap0.8' to the travis file? The configure script exits successfully after I install 'libpcap-dev' package in my Ubuntu VM, but 'libpcap0.8' is already installed.

**Comment by idosch** [comment]
Actually, in Ubuntu 19.10 I get:
$ apt-file find libpcap.pc
libpcap0.8-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/libpcap.pc

But:
$ apt show libpcap0.8-dev  
Package: libpcap0.8-dev
Version: 1.9.1-2

Whereas CI says:
Setting up libpcap0.8-dev (1.5.3-2) ...

So maybe this was fixed in later versions of the package?

**Comment by idosch** [comment]
Found this:
https://github.com/the-tcpdump-group/libpcap/commit/a7deb6a241f8c71ca261adc45ac07c8427074792#diff-4f6d5736c170750c6f430db12762116a

Looks like it's only present in libpcap-1.9.1

**Comment by nhorman** [comment]
yeah, I think the issue is that the github CI system is on an older ubuntu release

**Comment by LeSpocky** [comment]
This does also affect an ordinary build outside CI, if the host system has no bleeding edge pcap, like Debian 9 (stretch) or Debian 10 (buster):

```
configure: error: Package requirements (libpcap) were not met:

No package 'libpcap' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBPCAP_CFLAGS
and LIBPCAP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

(Note: I have `libpcap0.8-dev` installed, but as said above, pcap only starts shipping a pkg-config file with release 1.9. See Debian Bug [#922219](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922219) for reference.)

Up to libpcap 1.8.x there's no pkg-config file.

**Comment by nhorman** [comment]
resolved with https://github.com/nhorman/dropwatch/pull/21
