### ISSUE TITLE
dwdump source contains several compilation errors

### ISSUE THREAD

**Issue by nhorman** [nhorman/dropwatch#22]
With the fixing of the libpcap PKG_CHECK_MODULES issue ( issue #20 ), CI has found several compilation errors that need to be fixed for CI to pass:
https://travis-ci.org/github/nhorman/dropwatch/jobs/661916666
We need to correct those

**Comment by nhorman** [comment]
@idosch please look into this

**Comment by idosch** [comment]
Ack, checking

**Comment by nhorman** [comment]
thank you!

**Comment by idosch** [comment]
Ha, there are also errors with libpcap. I thought it's only libnl. Will fix those as well.

**Comment by nhorman** [comment]
thanks!

**Comment by idosch** [comment]
Travis CI now builds successfully, so I'm closing the issue.
