### ISSUE TITLE
build fails with -Wcast-align when cross-compiling for armv5

### ISSUE THREAD

**Issue by LeSpocky** [nhorman/dropwatch#26]
We usually set `-Wcast-align` in additional CFLAGS when cross-compiling for ARMv5 targets (see [this blog post](http://blog.antiblau.de/2016/07/13/cc-developers-please-use-wcast-align/) for explanation). This triggers the following warning (local build system paths shortened):

    make[1]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3'
    make  all-recursive
    make[2]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3'
    Making all in src
    make[3]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3/src'
      CC       main.o
    main.c: In function 'recv_netlink_message':
    main.c:297:25: error: cast increases required alignment of target type [-Werror=cast-align]
    cc1: all warnings being treated as errors
    Makefile:419: recipe for target 'main.o' failed
    make[3]: *** [main.o] Error 1
    make[3]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3/src'
    Makefile:429: recipe for target 'all-recursive' failed
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3'
    Makefile:361: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3'
    /usr/local/lib/ptxdist-2018.05.0/rules/post/ptxd_make_world_compile.make:21: recipe for target '***/platform-ncl/state/dropwatch.compile' failed
    make: *** [***/platform-ncl/state/dropwatch.compile] Error 2

The reason is this cast in line 297 of main.c:

<pre>
        msg = wrap_netlink_msg((struct nlmsghdr *)buf);
</pre>

Because dropwatch sets `-Werror` build fails. :slightly_frowning_face:

**Comment by nhorman** [comment]
See https://github.com/nhorman/dropwatch/pull/27

Please try your build with that PR and confirm that it solves your issue

**Comment by LeSpocky** [comment]
Confirmed.
