### ISSUE TITLE
dwdump can't configure drop monitor kernel module

### ISSUE THREAD

**Issue by eugene64** [nhorman/dropwatch#40]
"Failed to configure drop monitor kernel module" is written when providing any option, -o sw or -o hw.

nl_send_sync returns -1, "Unspecific error"

libnl libraries installed:
~/dropwatch$ dpkg -l | grep libnl
ii  libnl-3-200:amd64                      3.2.27-1ubuntu0.16.04.1                    amd64        library for dealing with netlink sockets
ii  libnl-3-dev:amd64                      3.2.27-1ubuntu0.16.04.1                    amd64        development library and headers for libnl-3
ii  libnl-genl-3-200:amd64                 3.2.27-1ubuntu0.16.04.1                    amd64        library for dealing with netlink sockets - generic netlink
ii  libnl-genl-3-dev:amd64                 3.2.27-1ubuntu0.16.04.1                    amd64        development library and headers for libnl-genl-3
ii  libnl-route-3-200:amd64                3.2.27-1ubuntu0.16.04.1                    amd64        library for dealing with netlink sockets - route interface

kernel:
Linux ubuntu-dev 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nhorman** [comment]
does your kernel have the drop_monitor module built?

**Comment by idosch** [comment]
Your kernel is too old. dwdump uses kernel features that were introduced in kernel version 5.4

**Comment by eugene64** [comment]
drop_monitor module is there.
5.4 is version introduced in 2020. Is it not possible to use drop watch on older kernels?
Most of production systems do not follow latest kernels that closely.

**Comment by idosch** [comment]
You can still use `dropwatch`, but not `dwdump`. Two different utilities.

**Comment by Vovans** [comment]
Have the same issue with 5.4.0 kernel

```
dwdump | tshark -Y 'udp.dstport==8004' -O net_dm -r -
Failed to configure drop monitor kernel module
```

And for dropwatch this 

```
dropwatch> start
Enabling monitoring...
Waiting for activation ack....
Failed activation request, error: Resource temporarily unavailable
Shutting down ...
```

**Comment by idosch** [comment]
On Fri, Jan 28, 2022 at 12:54:39AM -0800, Vovans wrote:
> Have the same issue with 5.4.0 kernel
> 
> ```
> dwdump | tshark -Y 'udp.dstport==8004' -O net_dm -r -
> Failed to configure drop monitor kernel module
> ```
> 
> And for dropwatch this 
> 
> ```
> dropwatch> start
> Enabling monitoring...
> Waiting for activation ack....
> Failed activation request, error: Resource temporarily unavailable
> Shutting down ...
> ```

Is it possible drop monitor is already tracing in the kernel?

**Comment by nhorman** [comment]
Thats most likely the case yes (The module returns EBUSY if you attempt to start it when its already started).  Just issue a stop command from dropwatch to stop it, then start it again with a start command.  Alternatively you can reset it by unloading and reloading the drop_monitor module

**Comment by jonwaland** [comment]
Similar issue - terminal crashed, and I presume the module is already loaded. I get "Failed activation request, error: Resource temporarily unavailable".

How do I unload the module? (Ubuntu)
