### ISSUE TITLE
Should we update Makefile License?

### ISSUE THREAD

**Issue by liuhangbin** [nhorman/dropwatch#48]
Hi Neil,

All our src codes are GPLv2+ License, while the Makefile.am is LGPLv2+ (Lesser General Public License). Would you update the Makefile license to GPLv2+?

Thanks
Hangbin

**Comment by nhorman** [comment]
Yeah, that would make sense, I'm not really sure what it even means to license an automake file as LGPL.  Want to post a PR?

**Comment by nhorman** [comment]
fixed in commit ab2965faeeb63fb22b938cc4c80a417b3bf7716b
