### ISSUE TITLE
[PETALINUX] Unable to find NET_DM family, dropwatch can't work

### ISSUE THREAD

**Issue by Masternick95** [nhorman/dropwatch#50]
I'm trying to use dropwatch on my petalinux installation on Xilinx zcu102 for debugging purposes. I have installed it following the instructions in README.md. However, when I try to run it with "dropwatch -lkas" it gives the following error:
"Unable to find NET_DM family, dropwatch can't work
Cleaning up on socket creation error"
How can this be fixed?

**Comment by nhorman** [comment]
you have to rebuild the kernel to enable drop monitoring support (CONFIG_NET_DROP_MONITOR).

**Comment by Masternick95** [comment]
thanks for the quick reply, however I have recompiled again the kernel with that option enabled. It was already enabled, but it does not works anyway

**Comment by nhorman** [comment]
is the option set to 'm' or 'y'?  If its set to 'm' then xilinx has probably messed up something in user space and alias loading isn't working.  You can work around it by manually running:
modprobe dropmonitor

Alternatively, its possible that they disabled some other kernel config that prevents the dropmonitor functionality from getting included.  Bottom line is that if you're getting the above error, it means that the running kernel doesn't have the NET_DM netlink family registered as an available protocol, so the user space components won't work.

Is there an alternate location I can download their kernel sources from? I find it pretty irritating that xlinix seems to have placed it behind a paywall, given that I wrote the code your asking about

**Comment by Masternick95** [comment]
Thanks, the option is set to 'y'. 
I don't know where you can dowload the kernel sources. However, I can send you a copy of my petalinux sample project with all the sources.

**Comment by nhorman** [comment]
just the config file from the running kernel please (you can get it from /proc/config.gz)
