### ISSUE TITLE
./configure fails to find libreadline

### ISSUE THREAD

**Issue by chrispsommers** [nhorman/dropwatch#59]
Install deps:
```
$ sudo apt-get install -y libnl-3-dev libnl-genl-3-dev binutils-dev libreadline6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
libnl-3-dev is already the newest version (3.2.29-0ubuntu3).
libnl-genl-3-dev is already the newest version (3.2.29-0ubuntu3).
libreadline-dev is already the newest version (7.0-3).
binutils-dev is already the newest version (2.30-21ubuntu1~18.04.7).
The following package was automatically installed and is no longer required:
  chromium-codecs-ffmpeg-extra
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 182 not upgraded.
```
Autogen:
```
$ ./autogen.sh 
+ mkdir -p m4
+ autoreconf -fv --install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:9: installing './compile'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
```
Configure fails:
```
./configure
...
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for READLINE... no
configure: error: libreadline is required
```
Find libreadline:
```
$ find /usr -name libreadline*
/usr/lib/x86_64-linux-gnu/libreadline.a
/usr/lib/x86_64-linux-gnu/libreadline.so
/usr/share/doc/libreadline-dev
/usr/share/doc/libreadline7
```
Any ideas? Thanks.

**Comment by nhorman** [comment]
Yes, please take 5 minutes to check your distribution website before you go assuming it's an upstream problem:
https://bugs.launchpad.net/ubuntu/+source/readline/+bug/1938591

Sorry I don't mean to seem irate, but you are literally the 8th person in the last two weeks to open an issue with me about this.  Ubuntu has been missing the .pc file for readline for years and has been too lazy  to do anything about it.  

Is something going on that so many people are trying to update stopwatch by hand?  I assume your trying to take advantage of some of the hardware monitor features?

If you would please, add a comment to the launchpad bug,  so that they see it's an issue affecting multiple people.  Perhaps they'll eventually wake up.

**Comment by chrispsommers** [comment]
Hi Neil! Thanks for taking the time to respond. I'm awfully sorry you're besieged with "issues" which are Ubuntu-caused. I've added my voice to the Launchpad page. I wouldn't have known to look at the distro website for pkg config issues, not everyone is an expert at diagnosing "build issues." Sorry if I added to your frustration!

Also, I don't understand this:
>Is something going on that so many people are trying to update stopwatch by hand?

I found an article https://netbeez.net/blog/how-to-monitor-packet-drops-dropwatch/ which extolled the virtues of dropwatch, which directed me to your repo, and I followed the instructions there to build it from source. So I am not updating it, I'm trying to build it for the first time. If there's a binary somewhere, I'd gladly download it.

One piece of advice - update your README to warn people of this issue and prevent them pestering you. Better yet, provide a workaround for us? Thanks, have a nice day, I appreciate your time.

**Comment by pjsnps** [comment]
oh yeah...

$ dnf search dropwatch
dropwatch.x86_64 : Kernel dropped packet monitor

$ sudo dnf install dropwatch
Installed:
  dropwatch-1.5-1.el8.x86_64                                                                                                                                                                                                                                     
Complete!

Much easier...

**Comment by nhorman** [comment]
ack

**Comment by nhorman** [comment]
correct, for some reason non LTS releases of ubuntu don't include dropwatch, but recent releases of ubuntu (21 and later I think), have a fixed readline package, so they should be able to build dropwatch as you note
