### ISSUE TITLE
Unable to cross compile for arm

### ISSUE THREAD

**Issue by deepakk97** [nhorman/dropwatch#62]
checking pkg-config is at least version 0.9.0... yes
checking for libnl-3.0... yes
checking for libnl-genl-3.0... yes
checking for readline... yes
checking for libpcap... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: 
configure: dropwatch Version:     1.5.3
configure: Target:                 
configure: Installation prefix:    /usr/local
configure: Compiler:               armv7-cortex_a7_v3-linux-gnueabihf-gcc
configure: Compiler flags: -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include/libnl3/
configure: BFD library support: no
INSTALL
make[5]: Entering directory '/home/dek2/sums_gds/sums1/build/CSeriesM7/apps/open-src/dropwatch/dropwatch-master'
Making install in src
make[6]: Entering directory '/home/dek2/sums_gds/sums1/build/CSeriesM7/apps/open-src/dropwatch/dropwatch-master/src'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
armv7-cortex_a7_v3-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/local/include/libnl3 -I/usr/local/include/libnl3 -I/usr/local/include -I/usr/local/include/ncurses -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include/libnl3/ -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lookup.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
armv7-cortex_a7_v3-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/local/include/libnl3 -I/usr/local/include/libnl3 -I/usr/local/include -I/usr/local/include/ncurses -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include/libnl3/ -MT lookup.o -MD -MP -MF $depbase.Tpo -c -o lookup.o lookup.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lookup_kas.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
armv7-cortex_a7_v3-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/local/include/libnl3 -I/usr/local/include/libnl3 -I/usr/local/include -I/usr/local/include/ncurses -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include/libnl3/ -MT lookup_kas.o -MD -MP -MF $depbase.Tpo -c -o lookup_kas.o lookup_kas.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link armv7-cortex_a7_v3-linux-gnueabihf-gcc -g -Wall -Werror -I/usr/local/include/libnl3 -I/usr/local/include/libnl3 -I/usr/local/include -I/usr/local/include/ncurses -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include -I/home/dek2/sums_gds/sums1/build/CSeriesM7/include/libnl3/ -L/home/dek2/sums_gds/sums1/build/CSeriesM7/lib -lnl-3 -L/usr/local/lib -lnl-genl-3 -lnl-3 -L/home/dek2/sums_gds/sums1/build/CSeriesM7/lib -lncurses -lpcap   -o dropwatch main.o lookup.o lookup_kas.o   
libtool: link: warning: library `/home/dek2/sums_gds/sums1/build/CSeriesM7/lib/libnl-genl-3.la' was moved.
libtool: link: cannot find the library `/usr/local/lib/libnl-3.la' or unhandled argument `/usr/local/lib/libnl-3.la'
make[6]: *** [Makefile:404: dropwatch] Error 1
make[6]: Leaving directory '/home/dek2/sums_gds/sums1/build/CSeriesM7/apps/open-src/dropwatch/dropwatch-master/src'
make[5]: *** [Makefile:414: install-recursive] Error 1
make[5]: Leaving directory '/home/dek2/sums_gds/sums1/build/CSeriesM7/apps/open-src/dropwatch/dropwatch-master'
make[4]: *** [Makefile:50: install] Error 2
make[4]: Leaving directory '/home/dek2/sums_gds/sums1/apps/open-src/dropwatch'
Populating the /home/dek2/sums_gds/sums1/build/CSeriesM7
Traceback (most recent call last):
  File "/home/dek2/sums_gds/sums1/tools/bin/sums_opkg_build.py", line 464, in <module>
    sys.exit( main() )
  File "/home/dek2/sums_gds/sums1/tools/bin/sums_opkg_build.py", line 458, in main
    ExtractOPKG(results.INFOPATH)
  File "/home/dek2/sums_gds/sums1/tools/bin/sums_opkg_build.py", line 255, in ExtractOPKG
    raise IOError("File %s not found" %(InfoPath))
OSError: File /home/dek2/sums_gds/sums1/build/CSeriesM7/OPKGS/dropwatch.json not found
make[3]: *** [/home/dek2/sums_gds/sums1/mk/sums-OPKG-support.mk:52: populate-dev-sysroot] Error 1
make[3]: Leaving directory '/home/dek2/sums_gds/sums1/apps/open-src/dropwatch'
make[2]: *** [/home/dek2/sums_gds/sums1/build/CSeriesM7/APPSBUILD-qaeqe0_e.mk:31: apps/open-src/dropwatch] Error 2
make[2]: Leaving directory '/home/dek2/sums_gds/sums1'
make[1]: *** [mk/sums_build.mk:17: app] Error 2
make[1]: Leaving directory '/home/dek2/sums_gds/sums1'
make: *** [app] Error 2

Although, libnl-genl-3.la is properly cross compiled and copied to the location

**Comment by nhorman** [comment]
well, it seems pretty clear that its not built properly, or it would be linking correctly.  The libnl-gen-3.a is just a text file that points to other library depednecies.  If you open libnl-genl-3.la with a text editor, you will almost certainly see that the dependency_libs  entry, or the reliink line points to loading the library /usr/local/lib/libnl-3.la, which I'm guessing isn't there.

Based on what you said above, I'm guessing that you just built libnl3, and then manually copied it to /home/dek2/sums_gds/sums1/build/CSeriesM7/lib
Instead build libnl3 by running:
./autogen.sh
./configure --prefix=/path/to/where/you/want/to/install
make
make install

**Comment by deepakk97** [comment]
Yes, Don't see proper links in libnl-3.la. 
Although I see proper links in other .la files that got generated.I did a little hack during libnl installation due to YAAC failures.Hope that's not causing issues?
 ./configure --host=$(CROSS_TARGET) --prefix=/usr/local   YACC="bison"

**Comment by nhorman** [comment]
You hacked the installation of libnl, were surprised to see it didn't work when building dropwatch, and assumed that its a failure in the latter rather than the former?  I don't know what exactly you did, but you need to fix your libnl installation prior to opening issues here.
