### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cboltz** [nhorman/dropwatch#67]
1.5.3 has been released two years ago, and in the meantime several things have been changed or fixed.

For example, the openSUSE Tumbleweed build for s390x is running into a [build failure](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/dropwatch/standard/s390x) which looks exactly like what what was fixed in commit 2093d1a4c0cd635edd5de38700ce4b0a404ba06d

Now of course we could include this (and maybe other) upstream commits as patches, but having a new release would make life easier for everybody ;-)

So - can you please provide a 1.5.4 release?

**Comment by nhorman** [comment]
done
