### ISSUE TITLE
Failed configure step for building Dropwatch

### ISSUE THREAD

**Issue by dpa456** [nhorman/dropwatch#70]
Hello, I was going to use dropwatch to do drop packet. However, the installation failed.
anything know about this?

error log
`error : configure: error: libreadline is required`

readline is already installed
`/sbin/ldconfig -p | grep readline `
>  libreadline.so.6 (libc6,x86-64) => /lib64/libreadline.so.6
> libreadline.so (libc6,x86-64) => /lib64/libreadline.so

Please let me know if you need any more information, thank you.

**Comment by nhorman** [comment]
yeah, I know that ubuntu users need to start twisting canonical arm to fix their distro:
https://bugs.launchpad.net/ubuntu/+source/readline/+bug/1938591
That bug has had dozens of people watching it for over a year now and no one at canonical seems to have the 5 minutes it would take to fix it.

**Comment by dpa456** [comment]
thank you for replay but so sad new  TAT
