### ISSUE TITLE
lookup_kas assumes an ordered file

### ISSUE THREAD

**Issue by Diego-Pennino** [nhorman/dropwatch#72]
Hi, using your software I noticed an anomalous behavior when using the "-l kas" option, the name resolution is not accurate. The look_kas.c file, assumes that the kallsyms file is sorted, which is not true in my case. 

In my case I solved it by creating a new sorted file and used look_kas.c, but a cleaner solution might be useful.

before:
2 drops at __entry_SYSCALL_64_trampoline+1ffbb6b06a7 (0xffffffffbbaaa6a7) [software]

after:
2 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]

**Comment by nhorman** [comment]
please upload a copy of your /proc/kallsyms before and after sorting.  I've never seen an unsorted symbol table, nor could I imagine why that would happen.

**Comment by Diego-Pennino** [comment]
[kallsyms.txt](https://github.com/nhorman/dropwatch/files/9596723/kallsyms.txt)
[kallsymsOrdered.txt](https://github.com/nhorman/dropwatch/files/9596724/kallsymsOrdered.txt)

**Comment by Diego-Pennino** [comment]
I found it strange to have unordered kallsyms, but both virtual and nonvirtual machines in my cases have unordered kallsyms. They all have Debian, but with different kernels.

**Comment by nhorman** [comment]
Thank you

So, Ugh.  Thats not good.  I note in the diff of your two files there are several sorts that shouldn't be relevant (i.e. the syscall trampolines, per-cpu data, and identical addresses).  The first two are all prior to any text symbols and so should get ignored by us.  the last one is the result of sorts that match on the address (i.e. multiple symbols pointing to the same addr, that got re-arranged by symbol alphabetical order).  But yeah, there are some module symbols that look to be a bit out of place

That all said, if I focus on the one symbol you reported above (unix_stream_connect), it seems like perhaps something more is going on here.  according to your kallsyms.txt file that symbol is located at 0xffffffffbbaaa120 and it appears in the file in earlier than the __entry_SYSCALL_* symbols.  that says to me the lookup code (prior to your sorting) should have matched on it, but didn't, allowing the search to continue until for some reason it hit on the __entry_SYSCALL symbols

the logic for the symbol lookup is:
for each line N in kallsyms, if [drop addr] > addr(N-1) AND [drop addr] < addr(N) THEN sym = sym(N-1)
which does assume an ordered list

looking at the lines in question:
ffffffffbbaaa120 t unix_stream_connect
ffffffffbbaaa6c0 t unix_dgram_sendmsg

and the [drop addr] 0xffffffffbbaaa6a7, when we parsed the line for unix_dgram_sendmsg, we should have seen that drop_addr was less than ffffffffbbaaa6c0 and that drop addr was greater than ffffffffbbaaa120, but we didn't, so I'll need to figure out why that is.  Let me do some playing to see whats going on there

**Comment by Diego-Pennino** [comment]
Thank you for the time you are spending on this issue


This is very strange to me.
I try to answer you as promptly and accurately as possible.
1) I am using version 1.5.4
2) my user also has access to the kallsyms file.

However it's very likely that it's just some problem on my environment since I'm the only one it gave this problem to.

Anyway I ran your changes and the behavior was the same:

 dropwatch -l kas
Initializing kallsyms db
lookup points to unix_stream_connect:1415


After this test I ran a start and launched some container dockers that don't do any action and this is what happens

dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
2 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]
2 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]
24 drops at netlink_broadcast_filtered+2b8 (0xffffffffbba27ac8) [software]
1 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
111 drops at __entry_SYSCALL_64_trampoline+1ffbb62dac8 (0xffffffffbba27ac8) [software]
1 drops at __entry_SYSCALL_64_trampoline+1ffbb5cdc4d (0xffffffffbb9c7c4d) [software]
1 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
7 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
14 drops at __entry_SYSCALL_64_trampoline+1ffbb5cdc4d (0xffffffffbb9c7c4d) [software]
1 drops at __entry_SYSCALL_64_trampoline+1ffbb6b06a7 (0xffffffffbbaaa6a7) [software]
7 drops at __entry_SYSCALL_64_trampoline+1ffbb5cdc4d (0xffffffffbb9c7c4d) [software]
4 drops at __entry_SYSCALL_64_trampoline+1ffbb6b06a7 (0xffffffffbbaaa6a7) [software]

It seems as if at some point things change under his nose and he can no longer function properly.

**Comment by nhorman** [comment]
Hmm, I wonder if we're getting some underflow error that results from some of the ordering issues you previously noted.    Specifically I'm wondering if we add a symbol to the cache, and its misordered, giving us a huge symbol range, leading to these crazy offsets.  Can you please build dropwatch with the attached patch and let me know when  you start seeing the __entry_SYSCALL messages, attaching the output if you can please?
[dropwatch.patch.txt](https://github.com/nhorman/dropwatch/files/9599571/dropwatch.patch.txt)

**Comment by Diego-Pennino** [comment]
dropwatch -l kas
Initializing kallsyms db
GOT CACHE HIT for unix_stream_connect
pc = 0xffffffffbbaaa6a7, sym start = 0xffffffffbbaaa120
lookup points to unix_stream_connect:1415
dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
GOT CACHE HIT for ip_rcv_finish_core.constprop.0
pc = 0xffffffffbba35f41, sym start = 0xffffffffbba35db0
2 drops at ip_rcv_finish_core.constprop.0+191 (0xffffffffbba35f41) [software]
GOT CACHE HIT for unix_stream_connect
pc = 0xffffffffbbaaa6a7, sym start = 0xffffffffbbaaa120
2 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffc06b2990, sym start = 0xfffffe00003fa000
2 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbb9c7c4d, sym start = 0xfffffe00003fa000
11 drops at __entry_SYSCALL_64_trampoline+1ffbb5cdc4d (0xffffffffbb9c7c4d) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbbaaa6a7, sym start = 0xfffffe00003fa000
8 drops at __entry_SYSCALL_64_trampoline+1ffbb6b06a7 (0xffffffffbbaaa6a7) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffc06b2990, sym start = 0xfffffe00003fa000
1 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbbaaa6a7, sym start = 0xfffffe00003fa000
1 drops at __entry_SYSCALL_64_trampoline+1ffbb6b06a7 (0xffffffffbbaaa6a7) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbba35f41, sym start = 0xfffffe00003fa000
1 drops at __entry_SYSCALL_64_trampoline+1ffbb63bf41 (0xffffffffbba35f41) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffc06b2990, sym start = 0xfffffe00003fa000
2 drops at __entry_SYSCALL_64_trampoline+1ffc02b8990 (0xffffffffc06b2990) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbb9c7c4d, sym start = 0xfffffe00003fa000
1 drops at __entry_SYSCALL_64_trampoline+1ffbb5cdc4d (0xffffffffbb9c7c4d) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbba27ac8, sym start = 0xfffffe00003fa000
29 drops at __entry_SYSCALL_64_trampoline+1ffbb62dac8 (0xffffffffbba27ac8) [software]
GOT CACHE HIT for __entry_SYSCALL_64_trampoline
pc = 0xffffffffbba27ac8, sym start = 0xfffffe00003fa000
29 drops at __entry_SYSCALL_64_trampoline+1ffbb62dac8 (0xffffffffbba27ac8) [software]

**Comment by nhorman** [comment]
Please give this:
https://github.com/nhorman/dropwatch/pull/74
A try.  It should ensure that we always find the symbol that is the minimal negative distance from the drop location reported

**Comment by Diego-Pennino** [comment]
Perfect, the new strategy is working correctly.




dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
1 drops at tcp_v6_rcv+44 (0xffffffffbbae3934) [software]
1 drops at tcp_v4_rcv+47 (0xffffffffbba604a7) [software]
6 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]
8 drops at unix_stream_connect+587 (0xffffffffbbaaa6a7) [software]
53 drops at netlink_broadcast_filtered+2b8 (0xffffffffbba27ac8) [software]
3 drops at nfnetlink_rcv_batch+410 (0xffffffffc06b2990) [software]
3 drops at skb_queue_purge+2d (0xffffffffbb9c7c4d) [software]
9 drops at nfnetlink_rcv_batch+410 (0xffffffffc06b2990) [software]



Thanks again for solving it

**Comment by nhorman** [comment]
ack, I'll merge it, thanks!
