### ISSUE TITLE
Unable to compile Dropwatch for OpenWrt

### ISSUE THREAD

**Issue by francescoraves483** [nhorman/dropwatch#76]
Hello,
I am trying to compile Dropwatch for OpenWrt, for an x86_64 platform based on the musl standard C library.
However, I am unable to complete the configuration of the project, both if I try compiling inside OpenWrt, or if I try cross-compiling the project from Ubuntu 20 LTS.

In the first case, "./configure" fails even if libnl is installed:
```
checking for LIBNL3... no
configure: error: libnl-3.0 is required

root@OpenWrt:~/dropwatch# opkg install libnl
Package libnl (3.3.0-1) installed in root is up to date.
```

I suppose this is probably due to the absence of libnl as a libXXX-dev package for OpenWrt.

When I try cross-compiling, instead, "./configure" returns an error on bfd.h:
```
/mnt/xtra/dropwatch$ ./configure --build=x86_64-unknown-linux-gnu --host=x86_64-openwrt-linux-musl
[...]
checking whether we are cross compiling... yes
[...]
checking bfd.h usability... no
checking bfd.h presence... no
checking for bfd.h... no
configure: error: Couldn't find or include bfd.h
```

The procedure does not fail if I just run "./configure" without any cross-compilation option.

Is this due to Dropwatch non supporting OpenWrt or musl-based systems? Or am I doing something wrong in the configuration procedure?

Thank you very much in advance.

**Comment by nhorman** [comment]
bfd.h isn't part of either glibc or musl, its part of binutils.  I suspect AC_CHECK_HEADERS in the configure.ac file is finding the bfd.h for the x86_64 platform when cross compiling, but unable to use it for the cross-build (its arch specific).

Your choices are:
1) install the binutils package in your cross systree
2) build without binutil support (i.e. ./configure --without-bfd).  this is probably a good option as bfd support isn't really finished (kas support really obviates it)
