### ISSUE TITLE
when i run the dropwatch iam not getting normal output of dropped packets

### ISSUE THREAD

**Issue by udhayNuk** [nhorman/dropwatch#77]
please solve my error 
@nhorman 
root@user-HP-Z420-WOrkstation:/home/user/Udhayakumar/DROPWATCH# dropwatch -l kas
Initializing kallsyms db
dropwatch> start
Enabling monitoring..
drop at: ip_rcv_finish_core.isra.0+0x1de/0x440 (0xffffffff96b6294e)
origin: software
input port ifindex: 3
timestamp: Thu Dec 22 13:14:21 2022 005165840 nsec
protocol: 0x800
length: 1358
original length: 1358

drop at: ip_rcv_finish_core.isra.0+0x1de/0x440 (0xffffffff96b6294e)
origin: software
input port ifindex: 3
timestamp: Thu Dec 22 13:14:21 2022 005166271 nsec
protocol: 0x800
length: 1358
original length: 1358

**Comment by nhorman** [comment]
whats not normal about your output?  It looks fine to me

**Comment by udhayNuk** [comment]
> whats not normal about your output? It looks fine to me
@nhorman 
This is an normal output,please reply me
dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
4 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software]
2 drops at net_tx_action+0 (0xffffffff9d5123d0) [software

And one more doubt i have how to save this output to a file?

**Comment by nhorman** [comment]
they're both normal outputs, I really don't know what you're getting at here.  The former dump just comes from a kernel that supports some newner netlink attributes for the dropwatch protocol

Saving the output? redirection.  i.e.:
echo "set alertlimit 10; start" | dropwatch -l kas > ./results

**Comment by nhorman** [comment]
closing for lack of update
