### ISSUE TITLE
Receive operation failed:: No buffer space available

### ISSUE THREAD

**Issue by rmbq** [nhorman/dropwatch#85]
Hi!
i'm using dropwatch to debug drops in my system.

I tried launching dropwatch with and without `-l kas`
I set it with `set sw 1` `set hw 0` `set alertmode packet`
Every time i have a drop dropwatch prints:
`Receive operation failed:: No buffer space available`
if i `set sw 0` `set hw 1` it prints nothing.
I can i debug this further?
Thanks

**Comment by nhorman** [comment]
I'd start by stracing dropwatch.  It sounds like you're system is memory constrained to the point that dropwatch is getting failures from the kerenel due to a full socket buffer.  A strace would confirm that
